# Generated by Django 4.2.2 on 2023-06-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon/'),
        ),
        migrations.AddField(
            model_name='navbarcategory',
            name='status',
            field=models.CharField(choices=[('navbar', 'Navbar'), ('sidebar', 'Sidebar')], default='navbar', max_length=100),
        ),
    ]
